url: https://y7kim.github.io
baseurl: /norman/

full_url: http://localhost:4000/norman/

# Site settings
title: Norman - Animation Studio
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram 
    url: https://www.instagram.com/normananimationstudio/
  - title: vimeo
    url: https://vimeo.com/normanstudio
  - title: behance
    url: https://www.behance.net/normanstudio
  - title: twitter
    url: https://twitter.com/norman_studio
  - title: facebook
    url: https://www.facebook.com/normananimation/

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty