url: http://norman.uy
baseurl: /norman-website/

full_url:  http://localhost:4000/norman/

# Site settings
title: Norman - Animation Studio
email: hola@norman.uy
description: "Norman is an animation studio company based in Uruguay with strong emphasis on 3D character animation."

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram 
    url: https://www.instagram.com/normananimationstudio/
  - title: vimeo
    url: https://vimeo.com/normanstudio
  - title: behance
    url: https://www.behance.net/normanstudio
  - title: twitter
    url: https://twitter.com/norman_studio
  - title: facebook
    url: https://www.facebook.com/normananimation/

# Postal address (add as many lines as necessary)
address:
  - line: Montevideo, Uruguay.

# Build settings
markdown: kramdown
permalink: pretty